# Task 1

In [24]:
import numpy as np
from scipy.ndimage.filters import convolve

In [21]:
def read_initial_state(file):
    """Reads the initial state from the file."""
    
    with open(file) as f:
        lines = f.readlines()
    
    data = []
    for line in lines:
        splitted = list(line[: -1])
        data_line = []
        for entry in splitted:
            data_line.append(0) if entry == '.' else data_line.append(1)
        data.append(data_line)

    return np.expand_dims(np.array(data), axis=0)

In [26]:
def update_grid(grid):
    """Swipes through the grid once."""
    dim0 = grid.shape[0] + 2
    dim1 = grid.shape[1] + 2
    dim2 = grid.shape[2] + 2
    new_grid = np.zeros((dim0, dim1, dim2))
    new_grid[1: -1, 1: -1, 1: -1] = grid.copy()
    
    # convolving through the array:
    filt = np.ones((3, 3, 3))
    filt[1, 1, 1] = 0
    filtered_grid = convolve(new_grid, filt, mode='constant', cval=0.0)
    
    # flattening the tensors into a row vector:
    new_grid = new_grid.flatten()
    filtered_grid = filtered_grid.flatten()
    for i, entry in enumerate(new_grid):
        if entry == 0:
            if filtered_grid[i] == 3:
                new_grid[i] = 1
        else:
            if filtered_grid[i] not in [2, 3]:
                new_grid[i] = 0
                
    return np.reshape(new_grid, (dim0, dim1, dim2))

In [27]:
# testing:
file = "data/test_data.txt"
grid = read_initial_state(file)
print(grid)
for _ in range(6):
    grid = update_grid(grid)

print("The number of active entryies is: {}".format(grid.sum()))

[[[0 1 0]
  [0 0 1]
  [1 1 1]]]
The number of active entryies is: 112.0


In [28]:
# real data:
file = "data/data.txt"
grid = read_initial_state(file)
print(grid)
for _ in range(6):
    grid = update_grid(grid)

print("The number of active entryies is: {}".format(grid.sum()))

[[[0 1 0 1 1 0 0 1]
  [0 0 0 0 1 0 1 1]
  [1 1 0 1 1 1 0 0]
  [0 1 0 1 0 1 1 1]
  [1 0 1 0 0 0 0 0]
  [0 1 0 0 1 1 1 0]
  [0 1 1 1 1 1 0 1]
  [1 0 0 1 1 1 1 0]]]
The number of active entryies is: 338.0


# Task 2

In [31]:
def read_initial_state_2(file):
    """Reads the initial state from the file."""
    
    with open(file) as f:
        lines = f.readlines()
    
    data = []
    for line in lines:
        splitted = list(line[: -1])
        data_line = []
        for entry in splitted:
            data_line.append(0) if entry == '.' else data_line.append(1)
        data.append(data_line)

    return np.array(data, ndmin=4)

In [33]:
def update_grid_2(grid):
    """Swipes through the grid once."""
    dim0 = grid.shape[0] + 2
    dim1 = grid.shape[1] + 2
    dim2 = grid.shape[2] + 2
    dim3 = grid.shape[3] + 2
    new_grid = np.zeros((dim0, dim1, dim2, dim3))
    new_grid[1: -1, 1: -1, 1: -1, 1: -1] = grid.copy()
    
    # convolving through the array:
    filt = np.ones((3, 3, 3, 3))
    filt[1, 1, 1, 1] = 0
    filtered_grid = convolve(new_grid, filt, mode='constant', cval=0.0)
    
    # flattening the tensors into a row vector:
    new_grid = new_grid.flatten()
    filtered_grid = filtered_grid.flatten()
    for i, entry in enumerate(new_grid):
        if entry == 0:
            if filtered_grid[i] == 3:
                new_grid[i] = 1
        else:
            if filtered_grid[i] not in [2, 3]:
                new_grid[i] = 0
                
    return np.reshape(new_grid, (dim0, dim1, dim2, dim3))

In [34]:
# testing:
file = "data/test_data.txt"
grid = read_initial_state_2(file)
print(grid)
for _ in range(6):
    grid = update_grid_2(grid)

print("The number of active entryies is: {}".format(grid.sum()))

[[[[0 1 0]
   [0 0 1]
   [1 1 1]]]]
The number of active entryies is: 848.0


In [35]:
# real data:
file = "data/data.txt"
grid = read_initial_state_2(file)
print(grid)
for _ in range(6):
    grid = update_grid_2(grid)

print("The number of active entryies is: {}".format(grid.sum()))

[[[[0 1 0 1 1 0 0 1]
   [0 0 0 0 1 0 1 1]
   [1 1 0 1 1 1 0 0]
   [0 1 0 1 0 1 1 1]
   [1 0 1 0 0 0 0 0]
   [0 1 0 0 1 1 1 0]
   [0 1 1 1 1 1 0 1]
   [1 0 0 1 1 1 1 0]]]]
The number of active entryies is: 2440.0
