# Task 1

In [1]:
import numpy as np

In [8]:
def read_and_sort(file):
    """Reads the file and returns a sorted numpy array with the data."""
    
    data = []
    with open(file) as f:
        for line in f:
            data.append(int(line[0: -1]))
            
    data.sort()
    return np.array(data)

In [22]:
def get_differences(data):
    """appends the zero and last adapter, which is bigger by 3 then the last one to the array and calculates the
    differences between the subsequent elements.
    """
    
    data = np.append(data, data[-1] + 3)
    data = np.append(np.array([0]), data)
    return data[1: ] - data[: -1]

In [24]:
# testing:
file = "data/test_data.txt"
data = read_and_sort(file)
differences = get_differences(data)
num_ones = np.count_nonzero(differences == 1)
num_threes = np.count_nonzero(differences == 3)
print("num of 1s: {}".format(num_ones))
print("num of 3s: {}".format(num_threes))
print("the multiplicative of them: {}".format(num_ones * num_threes))

num of 1s: 22
num of 3s: 10
the multiplicative of them: 220


In [33]:
# Real data:
file = "data/data.txt"
data = read_and_sort(file)
differences = get_differences(data)
num_ones = np.count_nonzero(differences == 1)
num_threes = np.count_nonzero(differences == 3)
print("num of 1s: {}".format(num_ones))
print("num of 3s: {}".format(num_threes))
print("the multiplicative of them: {}".format(num_ones * num_threes))

num of 1s: 70
num of 3s: 34
the multiplicative of them: 2380


In [35]:
np.count_nonzero(differences == 2)

0

# Task 2

In [31]:
def get_blocks(data):
    """Gets independent blocks from the data in which it is possible to leave out some
    elements and still get a valid series. Returns a list of np.arrays().
    """
    
    # augmenting the data with 0 at the beginning:
    data = np.append(np.array([0]), data)
    
    # running indices and other variables:
    i = 0
    blocks = []
    block = []
    
    # getting the blocks:
    while i < (data.shape[0] - 2):
        if (data[i + 2] - data[i]) < 3:
            block.append(data[i])
        else:
            if block:
                # appending the last 2 datapoints which still belong here:
                block.append(data[i])
                block.append(data[i + 1])
                # appending the new block to the list of blocks:
                blocks.append(np.array(block))
                block = []
        i += 1
        
    # appending the last block if it is not empty:
    if block:
        # appending the last 2 datapoints which still belong here:
        block.append(data[i])
        block.append(data[i + 1])
        # appending the new block to the list of blocks:
        blocks.append(np.array(block))
        block = []
    
    return blocks

In [38]:
def count_subsets(nums):
    """Counts the number of valid subsets of the array of numbers nums.
    Uses depth first search: The queue contains entries of the form:
            [index, bool, last_true]
    where index is the index of a value in the array and bool is whether to keep it in the array or not.
    last_true is the value of the last number that was kept in the series. 
    Actually the bool is not even used, but it helps the understanding of the code.
    The first and the last number has to be in the set, this is why a series is excepted if the last
    number was reached with it.
    """
    
    # appending the first 2 nodes of the tree:
    queue = []
    queue.append([1, True, nums[1]])
    queue.append([1, False, nums[0]])
    
    counter = 0
    
    while queue:
        # pop the last node::
        node = queue.pop()
        i = node[0]
        last_true = node[2]
        
        # Try to expand the last node:
        if (nums[i + 1] - last_true) <= 3:
            if (i + 1) == (nums.shape[0] - 1):
                # we have reached the end of the chain on this branch:
                counter += 1
            else:
                # expanding the node further by adding the 2 options to queue:
                queue.append([i + 1, True, nums[i + 1]])
                queue.append([i + 1, False, last_true])
    
    return counter

In [43]:
def count_all_possiblities(data):
    """Counts all possible combinations. It first divides the whole data into subsets.
    Then calculates the possible solutions for all subset. Then multiplies the possibilities
    together, since all blocks can be varies independently from eachother.
    """
    # splitting the data into blocks:
    blocks = get_blocks(data)
    
    # multiplying together the number of possibilities:
    counter = 1
    for block in blocks:
        counter *= count_subsets(block)
    
    return counter

In [39]:
# testing:
file = "data/test_data.txt"
data = read_and_sort(file)
print(data)
blocks = get_blocks(data)
print(blocks)

[ 1  2  3  4  7  8  9 10 11 14 17 18 19 20 23 24 25 28 31 32 33 34 35 38
 39 42 45 46 47 48 49]
[array([0, 1, 2, 3, 4]), array([ 7,  8,  9, 10, 11]), array([17, 18, 19, 20]), array([23, 24, 25]), array([31, 32, 33, 34, 35]), array([45, 46, 47, 48, 49])]


In [40]:
for block in blocks:
    print(block)
    num_of_subsets = count_subsets(block)
    print(num_of_subsets)

[0 1 2 3 4]
7
[ 7  8  9 10 11]
7
[17 18 19 20]
4
[23 24 25]
2
[31 32 33 34 35]
7
[45 46 47 48 49]
7


In [44]:
num_possibilities = count_all_possiblities(data)
print("The number of all possibilities: {}".format(num_possibilities))

The number of all possibilities: 19208


In [46]:
# real data:
file = "data/data.txt"
data = read_and_sort(file)
num_possibilities = count_all_possiblities(data)
print("The number of all possibilities: {}".format(num_possibilities))

The number of all possibilities: 48358655787008
